In [5]:
import numpy as np
import matplotlib.pyplot as plt
import copy, math

plt.style.use('deeplearning.mplstyle')
np.set_printoptions(precision=2)

# 2 Problem Statement

In [35]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [7]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [8]:
def f_wb(x, w, b):
    return np.dot(x,w)+b

In [9]:
# cost function
def compute_cost(x, y, w, b):
    sum_diff = 0
    for i in range(len(x)):
        y_pred = f_wb(x[i], w, b)
        sum_diff += (y_pred - y[i])**2
    return sum_diff/(2.0*len(x))

In [10]:
# w = [1, 2, 3, 4]
# b = 2
w = [0,0,0,0]
b = 0
print(X_train[0])
print(f_wb(X_train[0], w,b))
compute_cost(X_train, y_train, w, b)

[2104    5    1   45]
0


49518.0

In [11]:
def update_wb(x,y,w,b):
    m = len(x) # number of samples
    n = len(w) # number of features
    tmp_w = np.zeros(n)
    diff = np.zeros(n)
    for i in range(n):
        sum_dw = 0
        for j in range(m):
            diff[i] = (f_wb(x[j],w,b) - y[j])
            sum_dw += diff[i] * x[j, i]
            #print(f"x[{j}]={x[j]}, f_wb(x[{j}],w,b)={f_wb(x[j],w,b)}, y_train[{j}]={y_train[j]}, x[{j},{i}]={x[j,i]}, dw={(f_wb(x[j],w,b) - y_train[j]) * x[j, i]}, sum_dw={sum_dw}")
            #print(f"x[{j}]={x[j]}, f_wb(x[{j}],w,b)={f_wb(x[j],w,b)}, y_train[{j}]={y_train[j]}, sum_db={sum_db}")
        w[i] = w[i] - alpha /m * sum_dw
        b = b - alpha / m * np.sum(diff)
    # sum_db = 0
    # for j in range(m):
    #     sum_db += (f_wb(x[j],w,b) - y[j])
    # b = b - alpha / m * sum_db
    
    return w,b

In [33]:
# gradient descent
def derivative(x,y,w,b):
    global iterations
    lastcost = 1e9
    iteration = 0
    while True:
        iteration +=1
        cost = compute_cost(x,y,w,b)
        print(f"iter:{iteration:5}: w={w}, b={b}, cost={cost}")
        if abs(lastcost-cost)<neg or iteration>iterations:
            break
        else:
            lastcost = cost

        w,b = update_wb(x,y,w,b)
    return w,b

In [36]:
w = np.zeros(X_train[0].shape)
b = 0.
alpha = 5.0e-7
neg = 1e-3
iterations =9000
# w = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
# b = 785.1811367994083
w_final, b_final = derivative(X_train, y_train, w, b)


iter:    1: w=[0. 0. 0. 0.], b=0.0, cost=49518.0
iter:    2: w=[ 2.41e-01 -1.04e-04 -4.91e-05 -1.25e-03], b=9.104959712553112e-05, cost=2511.0426359060634
iter:    3: w=[ 1.95e-01 -7.99e-05 -5.34e-05 -1.10e-03], b=8.473829354027978e-05, cost=763.6833689697163
iter:    4: w=[ 2.04e-01 -8.06e-05 -6.62e-05 -1.21e-03], b=9.720147664120401e-05, cost=698.6643369885272
iter:    5: w=[ 2.02e-01 -7.66e-05 -7.75e-05 -1.28e-03], b=0.0001060466045867446, cost=696.2457917133688
iter:    6: w=[ 2.02e-01 -7.34e-05 -8.90e-05 -1.35e-03], b=0.00011559127539092716, cost=696.1438340950432
iter:    7: w=[ 2.02e-01 -7.01e-05 -1.00e-04 -1.42e-03], b=0.00012500299513306095, cost=696.1300704718542
iter:    8: w=[ 2.02e-01 -6.68e-05 -1.12e-04 -1.49e-03], b=0.0001344422803027175, cost=696.1191877241541
iter:    9: w=[ 2.02e-01 -6.35e-05 -1.23e-04 -1.57e-03], b=0.00014387818096763265, cost=696.1084898891701
iter:   10: w=[ 2.02e-01 -6.02e-05 -1.35e-04 -1.64e-03], b=0.00015331666462391606, cost=696.0977850116043
i

In [37]:
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

prediction: 430.10, target value: 460
prediction: 284.14, target value: 232
prediction: 165.17, target value: 178
