In [2]:
import numpy as np 
import time

In [3]:
a = np.zeros(4)
print(f"np.zeros(4):\na={a}, a shape={a.shape}, a data type={a.dtype}")
a = np.zeros((4,))
print(f"np.zeros((4,)):\na={a}, a shape={a.shape}, a data type={a.dtype}")
a = np.zeros((4,1))
print(f"np.zeros((4,1)):\na={a}, a shape={a.shape}, a data type={a.dtype}")

a = np.random.random_sample(4)
print(f"np.random.random_sample(4):\na={a}, a shape={a.shape}, a data type={a.dtype}")


np.zeros(4):
a=[0. 0. 0. 0.], a shape=(4,), a data type=float64
np.zeros((4,)):
a=[0. 0. 0. 0.], a shape=(4,), a data type=float64
np.zeros((4,1)):
a=[[0.]
 [0.]
 [0.]
 [0.]], a shape=(4, 1), a data type=float64
np.random.random_sample(4):
a=[0.97186767 0.15609525 0.43320263 0.38273281], a shape=(4,), a data type=float64


In [4]:
# [start, stop,step)
a = np.arange(4.0)
print(f"np.arange(4.0):\na = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.arange(0, 4.0, 1)
print(f"np.arange(0, 4.0, 1):\na = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.arange(3.9)
print(f"np.arange(3.9):\na = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4)
print(f"np.random.rand(4):\na = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.arange(4.0):
a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.arange(0, 4.0, 1):
a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.arange(3.9):
a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4):
a = [0.78889344 0.00277087 0.63549311 0.73556171], a shape = (4,), a data type = float64


In [5]:
a = np.array([5,4,3,2])
print(f"np.array([5,4,3,2]):\na = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.array([5.,4,3,2])
print(f"np.array([5.,4,3,2]):\na = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.array([5,4,3,2]):
a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5.,4,3,2]):
a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


## 3.4 Operations on Vectors


### 3.4.1 Indexing

In [6]:
a = np.arange(10)
print(a)

print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accessing an element returns a scalar")

print(f"a[-1] = {a[-1]}")

try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


### 3.4.2 Slicing

In [7]:
a = np.arange(10)

print(f"a       = {a}")

c = a[2:7:1];       print(f"a[2:7:1] = {c}")
c = a[2:7:2];       print(f"a[2:7:2] = {c}")
c = a[3:];          print(f"a[3:] = {c}")
c = a[:3];          print(f"a[:3] = {c}")
c = a[:];          print(f"a[:] = {c}")


a       = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


###  3.4.3 Single vector operations

In [8]:
a = np.array([1,2,3,4]);        print(f"a:{a}")

b = -a;                         print(f"-a:{b}")

b = np.sum(a);                  print(f"np.sum(a):{b}")

b = np.mean(a);                 print(f"np.mean(a):{b}")

b = a**2;                       print(f"a**2:{b}")


a:[1 2 3 4]
-a:[-1 -2 -3 -4]
np.sum(a):10
np.mean(a):2.5
a**2:[ 1  4  9 16]


### 3.4.4 Vector Vector element-wise operations


$c_i = a_i + b_i$

In [9]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,-3,-4])

print(f"Binary operators work element wise: {a+b}")

Binary operators work element wise: [0 0 0 0]


In [10]:
c = np.array([1,2])

try: 
    d = a+c
except Exception as e:
    print(f"The error message you will see is :{e}")

The error message you will see is :operands could not be broadcast together with shapes (4,) (2,) 


### 3.4.5 Scalar Vector operations

In [11]:
a = np.array([1,2,3,4])

b = 5*a
print(f"b = 5 * a: {b}")

b = 5 * a: [ 5 10 15 20]


### 3.4.6 Vector Vector dot product

dot product: $x = \sum^{n-1}_{i=0} a_i b_i$

Assume both $a$ and $b$ are the same shape.

In [12]:
def my_dot(a,b):
    dot_prod = 0
    for i in range(len(a)):
        dot_prod += a[i]*b[i]
    return dot_prod

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a,b)
# Note, the dot product is expected to return a scalar value. 
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b,a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


### 3.4.7 The Need for Speed: vector vs for loop

In [15]:


np.random.seed(1)
a = np.random.rand(10000000)
b = np.random.rand(10000000)

def get_run_time(f):
    tic = time.time()
    c = f(a,b)
    toc = time.time()
    return 1000*(toc-tic)

t = get_run_time(np.dot)

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {t:.4f} ms ")

t = get_run_time(my_dot)

print(f"my_dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {t:.4f} ms ")

del(a);del(b)

np.dot(a, b) =  24.0000
Vectorized version duration: 3.3197 ms 


my_dot(a, b) =  24.0000
Vectorized version duration: 2776.7825 ms 


So, vectorization provides a large speed up in this example. This is because **NumPy makes better use of available data parallelism in the underlying hardware**. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

### 3.4.8 Vector Vector operations in Course 1

In [16]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X = {X}")
print(f"c = {c}")

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X = [[1]
 [2]
 [3]
 [4]]
c = 4
X[1] has shape (1,)
w has shape (1,)
c has shape ()


# 4.Matrices

## 4.1 Abstract

## 4.2 NumPy Arrays

In numpy, matrices have a two-dimensional (2-D) index [m,n].

## 4.3 Matrix Creation

In [17]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1,1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((3,2))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]
a shape = (3, 2), a = [[0.04997798 0.77390955]
 [0.93782363 0.5792328 ]
 [0.53516563 0.80204309]]


In [18]:
a = np.array([[5], [4], [3]]);      print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],
             [4],
             [3]])
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


## 4.4 Operations on Matrices

### 4.4.1 Indexing

In [19]:
a = np.arange(6).reshape(-1,2) #reshape is a convenient way to create matrices
print(f"a.shape = {a.shape}, \na = {a}")

print(f"\na[2,0].shape = {a[2,0].shape}, a[2,0] = {a[2,0]}, type(a[2,0]) = {type(a[2,0])}")

print(f"\na[2].shape = {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")


a.shape = (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape = (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int64'>

a[2].shape = (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


Reshape

In [23]:
a = np.arange(6).reshape(-1, 2)
print(a)

# The -1 argument tells the routine to compute 
# the number of rows given the size of the array 
# and the number of columns.
a = np.arange(6).reshape(3, 2)
print(a)


[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


### 4.4.2 Slicing

In [28]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

print(f"a[0, 2:7:1] = {a[0, 2:7:1]}, a[0, 2:7:1].shape = {a[0, 2:7:1].shape}, 1-D array.")

print(f"a[0, 2:7:2] = {a[0, 2:7:2]}, a[0, 2:7:2].shape = {a[0, 2:7:2].shape}, 1-D array.")


print(f"a[:, 2:7:1] = {a[:, 2:7:1]}, a[:, 2:7:1].shape = {a[:, 2:7:1].shape}, 2-D array.")

print(f"a[:,:] = {a[:,:]}, a[:,:].shape = {a[:,:].shape}, 2-D array.")

print(f"a[1,:] = {a[1,:]}, a[1,:].shape = {a[1,:].shape}, 1-D array.")

print(f"a[1] = {a[1]}, a[1].shape = {a[1].shape}, 1-D array.")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], a[0, 2:7:1].shape = (5,), 1-D array.
a[0, 2:7:2] = [2 4 6], a[0, 2:7:2].shape = (3,), 1-D array.
a[:, 2:7:1] = [[ 2  3  4  5  6]
 [12 13 14 15 16]], a[:, 2:7:1].shape = (2, 5), 2-D array.
a[:,:] = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]], a[:,:].shape = (2, 10), 2-D array.
a[1,:] = [10 11 12 13 14 15 16 17 18 19], a[1,:].shape = (10,), 1-D array.
a[1] = [10 11 12 13 14 15 16 17 18 19], a[1].shape = (10,), 1-D array.
